name: build release apk

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build Release
        run: ./gradlew assembleRelease
      - name: Sign app APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed app apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Rename APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} /release/*.apk /tmp/simple24hclock.apk
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.release_notes.outputs.COMMITS }}
          generate_release_notes: true
          files: /tmp/simple24hclock.apk